# Generated by Django 5.2.7 on 2025-10-18 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=128)),
                ("nodes_config", models.JSONField(default=list)),
                ("scope_type", models.CharField(default="global", max_length=32)),
                ("scope_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "approval_flows",
            },
        ),
        migrations.CreateModel(
            name="DetectTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=128)),
                ("type", models.CharField(max_length=64)),
                ("api_url", models.URLField()),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_test_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "detect_tools",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="权限键"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="权限名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "权限",
                "verbose_name_plural": "权限管理",
                "db_table": "permissions",
            },
        ),
        migrations.RenameField(
            model_name="department",
            old_name="create_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="create_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="create_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="create_time",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="role",
            name="permission_keys",
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(max_length=64, unique=True, verbose_name="权限标识"),
        ),
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.AlterModelTable(
            name="role",
            table="roles",
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("ip", models.CharField(blank=True, max_length=64, null=True)),
                ("status", models.BooleanField(default=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "login_logs",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=128)),
                ("path", models.CharField(blank=True, max_length=256, null=True)),
                ("icon", models.CharField(blank=True, max_length=64, null=True)),
                ("sort", models.IntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="system.menu",
                    ),
                ),
            ],
            options={
                "db_table": "menus",
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=128)),
                (
                    "operator_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("operation_time", models.DateTimeField(auto_now_add=True)),
                ("ip", models.CharField(blank=True, max_length=64, null=True)),
                ("operation_content", models.TextField()),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("method", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "operation_logs",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                to="system.permission",
                verbose_name="权限集合",
            ),
        ),
        migrations.CreateModel(
            name="RoleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="system.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色关联",
                "verbose_name_plural": "用户角色关联",
                "db_table": "role_user",
                "unique_together": {("user", "role")},
            },
        ),
    ]
