# Generated by Django 5.2.7 on 2025-10-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["sort", "id"],
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
            },
        ),
        migrations.RemoveConstraint(
            model_name="menu",
            name="uk_parent_name",
        ),
        migrations.RemoveIndex(
            model_name="menu",
            name="idx_status",
        ),
        migrations.RemoveIndex(
            model_name="menu",
            name="idx_sort",
        ),
        migrations.AddField(
            model_name="menu",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="menus",
                to="auth.group",
                verbose_name="可见用户组",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="is_external",
            field=models.BooleanField(default=False, verbose_name="是否外链"),
        ),
        migrations.AddField(
            model_name="menu",
            name="permission",
            field=models.CharField(
                blank=True,
                default="",
                help_text="用于前端/后端细粒度权限控制，可留空",
                max_length=128,
                verbose_name="权限标识",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="是否显示"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="icon",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="图标"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="system.menu",
                verbose_name="父菜单",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="path",
            field=models.CharField(
                help_text="前端路由或后端URL；外链可填完整URL",
                max_length=255,
                unique=True,
                verbose_name="菜单路径",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="sort",
            field=models.PositiveIntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="uniq_parent_name"
            ),
        ),
        migrations.AlterModelTable(
            name="menu",
            table=None,
        ),
    ]
