# Generated by Django 5.2.7 on 2025-10-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerrequest",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system.position",
                verbose_name="申请岗位",
            ),
        ),
    ]
