# Generated by Django 5.2.7 on 2025-10-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("applicant", models.CharField(max_length=255, verbose_name="申请人")),
                ("department", models.CharField(max_length=100, verbose_name="部门")),
                ("end_user", models.CharField(max_length=255, verbose_name="最终用户")),
                ("description", models.TextField(verbose_name="项目描述")),
                ("plan_online_date", models.DateField(verbose_name="预计上线时间")),
                ("status", models.CharField(max_length=50, verbose_name="项目状态")),
                (
                    "base_image_version",
                    models.CharField(max_length=100, verbose_name="基础镜像版本"),
                ),
                ("components", models.JSONField(verbose_name="其他组件")),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目管理",
            },
        ),
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="流程名称"
                    ),
                ),
                ("nodes_config", models.JSONField(verbose_name="审批节点配置")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "审批流程配置",
                "verbose_name_plural": "审批流程配置",
                "db_table": "approval_flows",
                "indexes": [models.Index(fields=["status"], name="idx_flow_status")],
            },
        ),
        migrations.CreateModel(
            name="ProjectApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approver", models.CharField(max_length=255, verbose_name="审批人")),
                (
                    "approval_status",
                    models.CharField(max_length=50, verbose_name="审批状态"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="审批时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目审批",
                "verbose_name_plural": "项目审批管理",
            },
        ),
    ]
