# Generated by Django 5.2.7 on 2025-10-24 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("event_name", models.CharField(max_length=64, verbose_name="事件名")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="负载"),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("try_count", models.IntegerField(default=0, verbose_name="重试次数")),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="最后错误"),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次重试时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "通知外盒",
                "verbose_name_plural": "通知外盒",
                "db_table": "notification_outbox",
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="idx_outbox_status_next",
                    ),
                    models.Index(fields=["-created_at"], name="idx_outbox_ctime"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "enable_approval",
                    models.BooleanField(default=True, verbose_name="接收审批通知"),
                ),
                (
                    "enable_detect",
                    models.BooleanField(default=True, verbose_name="接收检测通知"),
                ),
                (
                    "enable_system",
                    models.BooleanField(default=True, verbose_name="接收系统通知"),
                ),
                (
                    "channel_websocket",
                    models.BooleanField(default=True, verbose_name="WebSocket推送"),
                ),
                (
                    "channel_email",
                    models.BooleanField(default=False, verbose_name="邮件推送"),
                ),
                (
                    "channel_sms",
                    models.BooleanField(default=False, verbose_name="短信推送"),
                ),
                (
                    "dnd_start",
                    models.TimeField(blank=True, null=True, verbose_name="免打扰开始"),
                ),
                (
                    "dnd_end",
                    models.TimeField(blank=True, null=True, verbose_name="免打扰结束"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_setting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知偏好",
                "verbose_name_plural": "通知偏好",
                "db_table": "notification_settings",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="模板编码"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPROVAL", "审批通知"),
                            ("DETECT", "检测通知"),
                            ("SYSTEM", "系统通知"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="模板类型",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="模板标题")),
                ("content", models.TextField(verbose_name="模板内容")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "通知模板",
                "verbose_name_plural": "通知模板",
                "db_table": "notification_templates",
                "indexes": [
                    models.Index(
                        fields=["type", "enabled"], name="idx_ntpl_type_enabled"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPROVAL", "审批通知"),
                            ("DETECT", "检测通知"),
                            ("SYSTEM", "系统通知"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNREAD", "未读"),
                            ("READ", "已读"),
                            ("ARCHIVED", "已归档"),
                        ],
                        db_index=True,
                        default="UNREAD",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "提示"), ("WARN", "警告"), ("ERROR", "错误")],
                        default="INFO",
                        max_length=8,
                        verbose_name="级别",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="标题"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "link_url",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="跳转链接"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="附加数据"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="去重键"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知消息",
                "verbose_name_plural": "通知消息",
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="idx_notice_user_status_ctime",
                    ),
                    models.Index(
                        fields=["user", "type", "-created_at"],
                        name="idx_notice_user_type_ctime",
                    ),
                    models.Index(fields=["dedup_key"], name="idx_notice_dedup"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedup_key", ""), _negated=True),
                        fields=("user", "dedup_key"),
                        name="uniq_user_dedup_when_present",
                    )
                ],
            },
        ),
    ]
