# Generated by Django 5.2.7 on 2025-10-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收用户",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(
                fields=["status", "next_retry_at"], name="idx_outbox_status_next"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(fields=["-created_at"], name="idx_outbox_ctime"),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_setting",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["type", "enabled"], name="idx_ntpl_type_enabled"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="idx_notice_user_status_ctime",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "type", "-created_at"],
                name="idx_notice_user_type_ctime",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["dedup_key"], name="idx_notice_dedup"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_key", ""), _negated=True),
                fields=("user", "dedup_key"),
                name="uniq_user_dedup_when_present",
            ),
        ),
    ]
