# Generated by Django 5.2.7 on 2025-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PROJECT", "项目报表"),
                            ("IMAGE", "镜像报表"),
                            ("BUSINESS_IMAGE", "业务镜像报表"),
                            ("BUSINESS_PROCESS", "业务流程报表"),
                        ],
                        max_length=64,
                        verbose_name="报表类型",
                    ),
                ),
                ("data", models.JSONField(verbose_name="报表数据")),
                ("period", models.CharField(max_length=64, verbose_name="时间段")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project_status",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="项目状态"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="部门"
                    ),
                ),
                (
                    "export_path",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="导出路径"
                    ),
                ),
            ],
            options={
                "verbose_name": "报表管理",
                "verbose_name_plural": "报表管理",
            },
        ),
    ]
