# Generated by Django 5.2.7 on 2025-10-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="镜像名称")),
                ("version", models.CharField(max_length=100, verbose_name="版本")),
                ("image_id", models.CharField(max_length=100, verbose_name="镜像ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("size", models.IntegerField(verbose_name="大小")),
                ("status", models.CharField(max_length=50, verbose_name="状态")),
                ("category", models.CharField(max_length=50, verbose_name="分类")),
                ("description", models.TextField(verbose_name="描述")),
            ],
            options={
                "verbose_name": "基础镜像",
                "verbose_name_plural": "基础镜像管理",
            },
        ),
        migrations.CreateModel(
            name="BusinessImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="镜像名称")),
                ("version", models.CharField(max_length=100, verbose_name="版本")),
                ("image_id", models.CharField(max_length=100, verbose_name="镜像ID")),
                (
                    "detect_status",
                    models.CharField(max_length=50, verbose_name="检测状态"),
                ),
                (
                    "approve_status",
                    models.CharField(max_length=50, verbose_name="审批状态"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("size", models.IntegerField(verbose_name="大小")),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "业务镜像",
                "verbose_name_plural": "业务镜像管理",
            },
        ),
    ]
