# Generated by Django 5.2.7 on 2025-10-23 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="仓库名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "系统"),
                            ("test", "测试"),
                            ("production", "生产"),
                        ],
                        max_length=64,
                        verbose_name="仓库类型",
                    ),
                ),
                (
                    "images_json",
                    models.JSONField(
                        help_text="存储仓库中镜像的 JSON 数据", verbose_name="镜像信息"
                    ),
                ),
                (
                    "environment_config",
                    models.JSONField(
                        help_text="不同环境的配置，系统、测试、生产",
                        verbose_name="环境配置",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_repositories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库管理",
                "verbose_name_plural": "仓库管理",
            },
        ),
    ]
